### ISSUE TITLE
GetImage() Return Values Question

### ISSUE THREAD

**Issue by ikaneshiro** [sylabs/scs-library-client#46]
Is there a reason to have the client `GetImage()` method return a false value instead of an error when an image is not found? This stems from this line https://github.com/sylabs/scs-library-client/blob/master/client/api.go#L227, and this comment from the singularity repo https://github.com/sylabs/singularity/pull/3736/files#r293967742. 

If the reasoning is to easily tell if an image is not found, imho it seems better to define and export the potential errors that could be encountered in this package so that the error type can be compared for that specific case.

**Comment by EmmEff** [comment]
Agreed. I am in favour of defining a const, like `ErrImageNotFound` or even `ErrNotFound` that we can use where it makes sense.

**Comment by mikegray** [comment]
Fixed in #48
