### ISSUE TITLE
Multi-architecture tag support

### ISSUE THREAD

**Issue by tri-adam** [sylabs/scs-library-client#49]
In order to support multi-arch for a given `path:tag`, I think we might want to add an (optional) architecture param to [DownloadImage()](https://godoc.org/github.com/sylabs/scs-library-client/client#Client.DownloadImage).

**Comment by dctrud** [comment]
Broadened the title of this a bit to encompass the work for multiple architectures per tag - which will involve changes beyond `DownloadImage()`

**Comment by EmmEff** [comment]
Resolved by #53
