### ISSUE TITLE
Multipart Uploader Missing Content Type

### ISSUE THREAD

**Issue by vsoch** [sylabs/scs-library-client#75]
I noticed here:

https://github.com/sylabs/scs-library-client/blob/30f9b6086f9764e0132935bcdb363cc872ac639d/client/request.go#L20

that the Multipart uploader doesn't include a content type, doesn't this introduce a [security risk](https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/missing-content-type-header/)? I've implemented [this once](https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L93) and remember that it was important to have. What are your thoughts, why don't you include it?

**Comment by dctrud** [comment]
Hi @vsoch - this code is a bit different than the multipart stuff you have for sregistry.

In the linked sregistry code it looks like you are making a single request for the upload where the metadata and data are uploaded as 'parts' in a multipart form POST. This is where you can e.g. upload some metadata and binary file data in a single POST request. The content-type must be set there (to `multipart/form-data`) so the server decodes the single POST request into separate parts properly.

The 'multipart' upload here is rather different - it's referring the S3 API's 'multipart' functionality (https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html), and not 'multipart form data'. Here many separate requests are being made, each uploading a chunk from the file. The requests are not multipart form-data, so the content-type isn't vital.

The security link you raise is for the other direction - where a server should specify a content type for files that are being downloaded, so a browser does not have to sniff it. This doesn't apply here, as we are uploading.

**Comment by vsoch** [comment]
@dctrud sorry the code I'm testing is not live on the sregistry github repository - it's using a different upload module for nginx that is implementing a (non form) data version, and it still seems to require the Content Type. What I was able to do is compile [this module](https://github.com/openresty/headers-more-nginx-module#installation) and then add it directly! So, I wonder if Sylabs can ever open source their registry? It sure would empower a lot of users to serve containers, which they cannot currently do, which is why I continue to maintain / work on Sregistry server.

My issue is resolved, so happy to close it here. Thanks!
